#!/usr/bin/php
<?php
// kernel/config.php <-- kernel/vendor/phasty/tman/src/(this)
require dirname(__FILE__).'/kernel/config.php';
$taskManager = new \Tman\TaskManager($argc, $argv);
$taskManager->run();
